version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - bitrix_var_www:/var/www/html
      - bitrix_etc_nginx:/etc/nginx
    networks:
      - proxy
    restart: on-failure

  # Webservers

  backend:
    build: ./httpd
    volumes:
      - bitrix_var_www:/var/www/html
    networks:
      - proxy
      - backend
    restart: on-failure

  # Databases

  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - bitrix_db_data:/var/lib/mysql
    networks:
      - backend
    restart: on-failure

networks:
  proxy:
  backend:

volumes:
  bitrix_db_data:
    driver: local
  bitrix_etc_nginx:
    driver: local
  bitrix_etc_apache:
    driver: local
  bitrix_etc_letsencrypt:
    driver: local
  bitrix_etc_php:
    driver: local
  bitrix_etc_mysql:
    driver: local
  bitrix_var_www:
    driver: local
  bitrix_etc_robocert:
    driver: local
